info:
  app:
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}
server:
  port: ${PORT:9801}

queue:
#  interval-cron: '0 0 1-2 * * *'
#  interval-cron: '*/10 * * * * *'
  interval-cron: '0 0 1 * * *'
  weather-cron: '0 36 11 * * *'
  enable: true
